apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dh4d61xi8-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dh4d61xi8-go 
  name: dh4d61xi8-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dh4d61xi8-go 
